image: openjdk:8-jdk

before_script:
  - chmod +x ./gradlew

stages:
  - test
  - build

test:
  stage: test
  script:
    - ./gradlew clean test

build:
  stage: build
  script:
    - ./gradlew build -i