dist: trusty
os: linux
language: java

env:
  global:
    - GRADLE_OPTS=-Xmx512m
    - CI=true

before_install:
  - nvm install 11
  - nvm use 11
  - chmod +x ./gradlew

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - ./gradlew clean test
        - ./gradlew build -i
        - npm i -g semantic-release && semantic-release