dist: trusty
os: linux
language: java

env:
  global:
    - GRADLE_OPTS=-Xmx512m
    - CI=true

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - wget https://install-node.now.sh
  - chmod +x ./gradlew

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew clean test
  - ./gradlew build -i

jobs:
  include:
    - stage: release
      node_js: lts/*
      script: npm i --no-save semantic-release && semantic-release