name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Tests
      run: ./gradlew clean test
    - name: Build with Gradle
      run: ./gradlew build -i
  release:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    name: Release
    steps:
      - name: Set up Node 12
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Semantic release
        run: npm i -g semantic-release && semantic-release
