name: Java CI

on: [push, pull_request]

jobs:
  write-version:
    runs-on: ubuntu-latest
    name: Write Version to File
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: List files
        run: ls -la
      - name: Update version
        uses: brettdorrans/write-version-to-file@master
        with:
          filename: './core/src/net/lapidist/colony/core/Constants.java'

  build:
    runs-on: ubuntu-latest
    name: Build
    needs: [write-version]
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      run: ./gradlew build -i

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Tests
      run: ./gradlew clean test
    - name: Run checkstyle
      run: ./gradlew check

  release:
    runs-on: ubuntu-latest
    needs: [build, test]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    if: github.ref == 'refs/heads/master'
    name: Release
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Semantic release
        run: npm i -g semantic-release && semantic-release
