name: Java CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '21' ]
    name: Test Java ${{ matrix.java }} 
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Tests with coverage
      run: |
        ./gradlew tests:copyAssets
        ./gradlew clean codeCoverageReport

    - name: Run style checks
      run: ./gradlew check


    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: bylapidist/colony
        files: build/reports/jacoco/codeCoverageReport/codeCoverageReport.xml
        fail_ci_if_error: true

  release:
    runs-on: ubuntu-latest
    needs: [test]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    if: github.ref == 'refs/heads/master'
    name: Release
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Semantic release
        run: |
          npm i -g semantic-release @semantic-release/changelog @semantic-release/git
          semantic-release

  pages:
    runs-on: ubuntu-latest
    needs: [release]
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: read
      pages: write
      id-token: write
    name: Deploy Docs
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Generate Javadoc
        run: |
          ./gradlew tests:copyAssets
          ./gradlew aggregateJavadocs

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/docs/javadoc

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
