name: Java CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '21' ]
    name: Test Java ${{ matrix.java }} 
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-disabled: true

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Tests with coverage
      run: |
        ./gradlew tests:copyAssets
        ./gradlew clean jacocoTestReport

    - name: Run style checks
      run: ./gradlew check

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: bylapidist/colony

  release:
    runs-on: ubuntu-latest
    needs: [test]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    if: github.ref == 'refs/heads/master'
    name: Release
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Semantic release
        run: |
          npm i -g semantic-release @semantic-release/changelog @semantic-release/git
          semantic-release
