name: Java CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: 15
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Tests
      run: ./gradlew clean test
    - name: Run checkstyle
      run: ./gradlew check

  release:
    runs-on: ubuntu-latest
    needs: [test]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    if: github.ref == 'refs/heads/master'
    name: Release
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Semantic release
        run: npm i -g semantic-release && semantic-release